package ws.bmocanu.aoc.ed2021;

public class Day24_GeneratedRunner {

    static int[] number = new int[14];

    public static void main(String[] args) {
        long currentNr = Long.parseLong(args[0]);
        int w, x, y, index = 0;
        int z = 1;

        monad_loop:
        while (z != 0) {
            w = x = y = z = 0;
            currentNr--;
            //System.out.println(currentNr);
            long splitNr = currentNr;
            for (int digitIndex = 13; digitIndex >= 0; digitIndex--) {
                if (splitNr % 10 == 0) {
                    z = 1;
                    continue monad_loop;
                }
                number[digitIndex] = (int) splitNr % 10;
                splitNr = splitNr / 10;
            }
            index = 0;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 15;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 9;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 11;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 1;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 10;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 11;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 12;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 3;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -11;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 10;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 11;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 5;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 14;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 0;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -6;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 7;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 1;
            x = x + 10;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 9;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -6;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 15;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -6;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 4;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -16;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 10;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -4;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 4;
            y = y * x;
            z = z + y;
            w = number[index];
            index++;
            x = x * 0;
            x = x + z;
            x = x % 26;
            z = z / 26;
            x = x + -2;
            x = x == w ? 1 : 0;
            x = x == 0 ? 1 : 0;
            y = y * 0;
            y = y + 25;
            y = y * x;
            y = y + 1;
            z = z * y;
            y = y * 0;
            y = y + w;
            y = y + 9;
            y = y * x;
            z = z + y;
        }
    }
}